Update workflows

diff --git a/.github/workflows/schemacrawler-job.yml b/.github/workflows/schemacrawler-job.yml
--- a/.github/workflows/schemacrawler-job.yml
+++ b/.github/workflows/schemacrawler-job.yml
@@ -23,18 +23,20 @@ jobs:
           USER: user-possibly-from-secrets
           PASSWORD: password-possibly-from-secrets
 
-      - id: check-success
-        name: Check if the SchemaCrawler run succeeded
-        run: |
-          [ ${{ steps.schemacrawler.outputs.exit_status }} -eq 0 ] && echo "SchemaCrawler run succeeded" || exit ${{ steps.schemacrawler.outputs.exit_status }}
-      
       - id: checkin
-        name: Checkin schema diagram created from the SchemaCrawler Action
+        name: Checkin schema diagram created by the SchemaCrawler Action
         run: |
           git config user.name github-actions
           git config user.email github-actions@github.com
           git config pull.rebase true
           git add db_diagram.png
-          git commit -m "SchemaCrawler schema diagram generated from GitHub action"
+          git commit -m "Schema diagram generated by SchemaCrawler Action for GitHub Actions"
           git pull
           git push
+
+      - id: check-success
+        name: Fail the entire job if SchemaCrawler run failed
+        run: |
+          [ ${{ steps.schemacrawler.outputs.exit_status }} -eq 0 ] && echo "SchemaCrawler lint check succeeded" || echo "SchemaCrawler run failed"
+          [ ${{ steps.schemacrawler.outputs.exit_status }} -eq 0 ] || exit 1
+
