Update mermaid diagram generation to create file

diff --git a/.github/workflows/schemacrawler-mermaid.yml b/.github/workflows/schemacrawler-mermaid.yml
--- a/.github/workflows/schemacrawler-mermaid.yml
+++ b/.github/workflows/schemacrawler-mermaid.yml
@@ -1,4 +1,4 @@
-name: SchemaCrawler Job to Lint Database Schema
+name: SchemaCrawler Job to Generate mermaid Diagram
 
 on: [push]
 
@@ -6,7 +6,7 @@ jobs:
   schemacrawler-job:
     runs-on: ubuntu-latest
 
-    name: SchemaCrawler Job to Lint Database Schema
+    name: SchemaCrawler Job to Generate mermaid Diagram
     steps:
 
       - id: checkout
@@ -18,21 +18,28 @@ jobs:
         uses: schemacrawler/SchemaCrawler-Action@v16.12.2
         with:
           entrypoint: /schemacrawler.sh
-          args: --server=sqlite --database=schemacrawler.sqlite --info-level=standard --command  script --tables "Authors|Books|BookAuthors" --script-language python --script mermaid.py --output-file mermaid-er.txt --log-level=FINE
+          args: --server=sqlite --database=schemacrawler.sqlite --info-level=standard --command  script --tables "Authors|Books|BookAuthors" --script-language python --script mermaid.py --output-file mermaid-er.mmd --log-level=FINE
         env:
           USER: user-possibly-from-secrets
           PASSWORD: password-possibly-from-secrets
+
+      - id: generate-diagram
+        name: Generate mermaid diagram
+        run: |
+          # Generate mermaid diagram
+          npm install @mermaid-js/mermaid-cli
+          ./node_modules/.bin/mmdc -i mermaid-er.mmd -o mermaid-er.png -s 3
 
       - id: upload-mermaid-er
         name: Upload SchemaCrawler mermaid diagram
         uses: actions/upload-artifact@v2
         with:
           name: mermaid-er
-          path: mermaid-er.txt
+          path: mermaid-er.*
 
       - id: check-success
-        name: Fail the entire job if SchemaCrawler lint report has failures
+        name: Fail the entire job if SchemaCrawler mermaid diagram generation has failures
         run: |
-          [ ${{ steps.schemacrawler.outputs.exit_status }} -eq 0 ] && echo "SchemaCrawler mermaid diagram generation succeeded" || echo "SchemaCrawler lint check shows failures - see the lint report"
+          [ ${{ steps.schemacrawler.outputs.exit_status }} -eq 0 ] && echo "SchemaCrawler mermaid diagram generation succeeded" || echo "SchemaCrawler mermaid diagram generation failed"
           [ ${{ steps.schemacrawler.outputs.exit_status }} -eq 0 ] || exit 1
 
