Publish artifacts to job results

diff --git a/.github/workflows/schemacrawler-job.yml b/.github/workflows/schemacrawler-job.yml
--- a/.github/workflows/schemacrawler-job.yml
+++ b/.github/workflows/schemacrawler-job.yml
@@ -18,24 +18,20 @@ jobs:
         uses: schemacrawler/SchemaCrawler-Action@v16.11.5
         with:
           entrypoint: /schemacrawler.sh
-          args: --server=sqlite --database=schemacrawler.sqlite --user:env USER --password:env PASSWORD --info-level=standard --command=brief --output-file db_diagram.png --log-level=CONFIG
+          args: --server=sqlite --database=schemacrawler.sqlite --user:env USER --password:env PASSWORD --info-level=standard --command=brief --output-file database-diagram.png --log-level=CONFIG
         env:
           USER: user-possibly-from-secrets
           PASSWORD: password-possibly-from-secrets
 
-      - id: checkin
-        name: Checkin schema diagram created by the SchemaCrawler Action
-        run: |
-          git config user.name github-actions
-          git config user.email github-actions@github.com
-          git add db_diagram.png
-          git commit -m "Schema diagram generated by SchemaCrawler Action for GitHub Actions"
-          git pull
-          git push
+      - id: upload-lint-report
+        name: Upload SchemaCrawler database diagram
+        uses: actions/upload-artifact@v2
+        with:
+          name: database-diagram
+          path: database-diagram.png
 
       - id: check-success
         name: Fail the entire job if SchemaCrawler run failed
         run: |
-          [ ${{ steps.schemacrawler.outputs.exit_status }} -eq 0 ] && echo "SchemaCrawler lint check succeeded" || echo "SchemaCrawler run failed"
+          [ ${{ steps.schemacrawler.outputs.exit_status }} -eq 0 ] && echo "SchemaCrawler run succeeded" || echo "SchemaCrawler run failed"
           [ ${{ steps.schemacrawler.outputs.exit_status }} -eq 0 ] || exit 1
-
