Show error message if lint fails

diff --git a/.github/workflows/schemacrawler-lint.yml b/.github/workflows/schemacrawler-lint.yml
--- a/.github/workflows/schemacrawler-lint.yml
+++ b/.github/workflows/schemacrawler-lint.yml
@@ -25,7 +25,6 @@ jobs:
 
       - id: checkin
         name: Checkin lint report created from the SchemaCrawler Action
-        if: false
         run: |
           git config user.name github-actions
           git config user.email github-actions@github.com
@@ -38,5 +37,6 @@ jobs:
       - id: check-success
         name: Fail the entire job if SchemaCrawler found any database lints
         run: |
-          [ ${{ steps.schemacrawler.outputs.exit_status }} -eq 0 ] && echo "SchemaCrawler run succeeded" || exit ${{ steps.schemacrawler.outputs.exit_status }}
+          [ ${{ steps.schemacrawler.outputs.exit_status }} -eq 0 ] && echo "SchemaCrawler lint check succeeded" || echo "SchemaCrawler lint check shows failures - see the lint report"
+          [ ${{ steps.schemacrawler.outputs.exit_status }} -eq 0 ] || exit 1
 
